/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2015-05-04 18:22:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class _403_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsecurity_005fauthorize_0026_005faccess;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsecurity_005fauthorize_0026_005faccess = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fsecurity_005fauthorize_0026_005faccess.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE>\n");
      out.write("\t<html>\n");
      out.write("\t\t<head>\n");
      out.write("\t\t\t<meta charset=\"utf=8\">\n");
      out.write("      \t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("      \t\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js\"></script>\n");
      out.write("      \t\t<script src=\"bootstrap/bootstrap-3.3.2-dist/js/bootstrap.min.js\"></script>\n");
      out.write("      \t\t<link href=\"bootstrap/bootstrap-3.3.2-dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("      \t\t<link rel=\"stylesheet\" href=\"http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css\">\n");
      out.write("\t\t\t<link href=\"css/general_layout_override.css\" rel=\"stylesheet\">\n");
      out.write("\t\t\t<script src=\"js/main_functions.js\"></script>\n");
      out.write("      \t\t<title>MEDEM :: Atención</title>\n");
      out.write("\t\t</head>\n");
      out.write("\t\t\n");
      out.write("\t\t<body id=\"dashboard\">\n");
      out.write("\t\t\n");
      out.write("\t\t\t<nav class=\"navbar navbar-default\" role=\"navigation\">\n");
      out.write("\t\t\t  <!-- csrt for log out-->\n");
      out.write("\t\t\t  ");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("  \t\t\t  <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${logoutUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" method=\"post\" id=\"logoutForm\">\n");
      out.write("\t  \t\t    <input type=\"hidden\" name=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.parameterName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\n");
      out.write("\t\t\t  </form>\n");
      out.write("\n");
      out.write("\t\t\t  <div class=\"navbar-header\">\n");
      out.write("\t\t        <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">\n");
      out.write("\t\t          <span class=\"sr-only\">Toggle navigation</span> <span class=\"icon-bar\"></span><span class=\"icon-bar\"></span><span class=\"icon-bar\"></span>\n");
      out.write("\t\t        </button>\n");
      out.write("\t\t        <a class=\"navbar-brand\" href=\"http://www.jquery2dotnet.com\">MEDEM</a>\t\t\t\t\n");
      out.write("\t\t\t  </div><!-- .navbar-header -->\n");
      out.write("\t\t\t  <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\n");
      out.write("\t\t\t    <ul class=\"nav navbar-nav\">\n");
      out.write("\t\t          <li class=\"active\"><a href=\"#\"><span class=\"glyphicon glyphicon-home\"></span> Inicio</a></li>\n");
      out.write("\t\t          <li class=\"dropdown\"><a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"><span class=\"glyphicon glyphicon-user\"></span> Empleados <b class=\"caret\"></b></a>\n");
      out.write("\t\t            <ul class=\"dropdown-menu\">\n");
      out.write("\t\t              <li><a href=\"employee\">\n");
      out.write("\t\t                <span class=\"glyphicon glyphicon-plus-sign\"></span> Crear Empleado</a>\n");
      out.write("\t\t              </li>\n");
      out.write("\t\t              <li><a href=\"indexEmployees\">\n");
      out.write("\t\t                <span class=\"glyphicon glyphicon-list-alt\"></span> Listar Empleados</a>\n");
      out.write("\t\t              </li>\n");
      out.write("\t\t              <li>\n");
      out.write("\t\t                <a href=\"#\"><span class=\"glyphicon glyphicon-search\"></span> Buscar Empleado</a>\n");
      out.write("\t\t              </li>\n");
      out.write("\t\t            </ul>\n");
      out.write("\t\t          </li>\t\n");
      out.write("\t\t          <li class=\"dropdown\"><a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"><span class=\"glyphicon glyphicon-bookmark\"></span> Empresas <b class=\"caret\"></b></a>\n");
      out.write("\t\t            <ul class=\"dropdown-menu\">\n");
      out.write("\t\t              <li><a href=\"newCompany\">\n");
      out.write("\t\t                <span class=\"glyphicon glyphicon-plus-sign\"></span> Crear Empresa</a>\n");
      out.write("\t\t              </li>\n");
      out.write("\t\t              <li><a href=\"indexCompany\">\n");
      out.write("\t\t                <span class=\"glyphicon glyphicon-list-alt\"></span> Listar Empresa</a>\n");
      out.write("\t\t              </li>\n");
      out.write("\t\t              <li>\n");
      out.write("\t\t                <a href=\"#\"><span class=\"glyphicon glyphicon-search\"></span> Buscar Empresa</a>\n");
      out.write("\t\t              </li>\n");
      out.write("\t\t    \t\t</ul>\n");
      out.write("\t\t    \t  </li>\n");
      out.write("\t\t          <li class=\"dropdown\"><a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"><span class=\"glyphicon glyphicon-flag\"></span> Areas <b class=\"caret\"></b></a>\n");
      out.write("\t\t            <ul class=\"dropdown-menu\">\n");
      out.write("\t\t              <li><a href=\"newArea?companyId=1\">\n");
      out.write("\t\t    \t\t    <span class=\"glyphicon glyphicon-plus-sign\"></span> Crear Area</a>\n");
      out.write("\t\t              </li>\n");
      out.write("\t\t              <li><a href=\"indexAreas?companyId=1\">\n");
      out.write("\t\t                <span class=\"glyphicon glyphicon-list-alt\"></span> Listar Areas</a>\n");
      out.write("\t\t              </li>\n");
      out.write("\t\t    \t\t</ul>\n");
      out.write("\t\t          </li>\t\n");
      out.write("\t\t          ");
      if (_jspx_meth_security_005fauthorize_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t    </ul><!-- .nav navbar-nav -->\n");
      out.write("\t\t\t    <ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("\t\t          <li class=\"dropdown\"><a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"><span class=\"glyphicon glyphicon-user\"></span> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(" <b class=\"caret\"></b></a>\n");
      out.write("\t\t            <ul class=\"dropdown-menu\">\n");
      out.write("\t\t              <li><a href=\"#\"><span class=\"glyphicon glyphicon-user\"></span> Perfil</a></li>\n");
      out.write("\t\t              <li class=\"divider\"></li>\n");
      out.write("\t\t              <li><a href=\"javascript:logoutFormSubmit();\"><span class=\"glyphicon glyphicon-off\"></span> Logout</a></li>\n");
      out.write("\t\t            </ul>\n");
      out.write("\t\t          </li>\t\t\t\t\t\n");
      out.write("\t\t\t    </ul><!-- .nav navbar-nav navbar-right -->\n");
      out.write("\t\t\t  </div><!-- .collapse navbar-collapse -->\n");
      out.write("\t\t\t</nav><!-- .navbar navbar-default -->\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t  <div class=\"col-md-12\">\n");
      out.write("\t\t\t    <div class=\"row\">\n");
      out.write("\t\t\t      <div class=\"panel panel-default\">\n");
      out.write("\t\t\t        <div class=\"panel-heading\">\n");
      out.write("\t\t\t        \t<h3 class=\"panel-title\">Atención</h3>\n");
      out.write("\t\t\t        </div>\n");
      out.write("\t\t\t        <div class=\"panel-body\">\n");
      out.write("\t\t\t          <span class=\"text-danger\"><h3><span class=\"glyphicon glyphicon-warning-sign\n");
      out.write("\t\t\t          \"></span> 403 -Recurso de acceso restringido</h3></span>\n");
      out.write("\t\t\t          <p><a href=\"/medem\" class=\"btn btn-primary\"><span class=\"glyphicon glyphicon-home\"></span> Inicio</a></p>\n");
      out.write("\t\t\t        </div><!-- .panel-body -->\n");
      out.write("\t\t\t      </div><!-- .panel panel-default -->\n");
      out.write("\t\t\t    </div><!--  .row -->\n");
      out.write("\t\t\t  </div><!-- .col-md-12 -->\n");
      out.write("\t\t\t</div>\t\n");
      out.write("\t\t\n");
      out.write("\t\t</body>\n");
      out.write("\t</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /WEB-INF/pages/403.jsp(23,5) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/j_spring_security_logout");
    // /WEB-INF/pages/403.jsp(23,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setVar("logoutUrl");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_security_005fauthorize_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  security:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_security_005fauthorize_005f0 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsecurity_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    _jspx_th_security_005fauthorize_005f0.setPageContext(_jspx_page_context);
    _jspx_th_security_005fauthorize_005f0.setParent(null);
    // /WEB-INF/pages/403.jsp(73,12) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_security_005fauthorize_005f0.setAccess("hasRole('ROLE_ADMIN')");
    int _jspx_eval_security_005fauthorize_005f0 = _jspx_th_security_005fauthorize_005f0.doStartTag();
    if (_jspx_eval_security_005fauthorize_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      out.write("\n");
      out.write("\t\t          <li class=\"dropdown\"><a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"><span class=\"glyphicon glyphicon-stats\"></span> Reportes <b class=\"caret\"></b></a>\n");
      out.write("\t\t            <ul class=\"dropdown-menu\">\n");
      out.write("\t\t              <li><a href=\"reportCharts\">\n");
      out.write("\t\t                <span class=\"glyphicon glyphicon-plus-sign\"></span> Generar Reporte</a>\n");
      out.write("\t\t              </li>\n");
      out.write("\t\t            </ul>\n");
      out.write("\t\t          </li>\t                                \t\t\n");
      out.write("\t\t          ");
    }
    if (_jspx_th_security_005fauthorize_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fsecurity_005fauthorize_0026_005faccess.reuse(_jspx_th_security_005fauthorize_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fsecurity_005fauthorize_0026_005faccess.reuse(_jspx_th_security_005fauthorize_005f0);
    return false;
  }
}
