/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2015-05-08 17:33:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class medicalNote_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005fmethod_005faction;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005fmethod_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005fmethod_005faction.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE>\n");
      out.write("  <html>\n");
      out.write("    <head>\n");
      out.write("      <meta charset=\"utf=8\">\n");
      out.write("      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("      <link rel=\"stylesheet\" href=\"http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css\">\n");
      out.write("      <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js\"></script>\n");
      out.write("      <link href=\"bootstrap/bootstrap-3.3.2-dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("      <link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css\">\n");
      out.write("      <link href=\"css/general_layout_override.css\" rel=\"stylesheet\">\n");
      out.write("      <script src=\"bootstrap/bootstrap-3.3.2-dist/js/bootstrap.min.js\"></script>\n");
      out.write("      <script src=\"http://code.jquery.com/ui/1.11.4/jquery-ui.js\"></script>\n");
      out.write("      <script src=\"js/main_functions.js\"></script>\n");
      out.write("      <title>MEDEM :: Empleado :: Nueva Nota Medico</title>\n");
      out.write("    </head>\n");
      out.write("\n");
      out.write("    <body id=\"medicalNote\">\n");
      out.write("\n");
      out.write("      ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "layouts/navigation_layout.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("      <div class=\"container\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("          <div class=\"panel-body\">\n");
      out.write("            <h1 class=\"page-header patient_name\">\n");
      out.write("              Empleado\n");
      out.write("            </h1><!-- .page-header patient_name -->  \n");
      out.write("            <div class=\"panel-body\">\n");
      out.write("\n");
      out.write("              <ul class=\"nav nav-tabs\">\n");
      out.write("                <li><a href=\"employeeShow?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employee_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">Ficha de Identificaci&#243;n</a></li>\n");
      out.write("                <li><a href=\"workBackground?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employee_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">Antecedentes Laborales</a></li>\n");
      out.write("                <li><a href=\"familyHistory?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employee_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">Antecedentes Heredofamiliares</a></li>\n");
      out.write("                <li><a href=\"medicalRecord?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employee_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">Historia Clinica</a></li>\n");
      out.write("                <li><a href=\"medicalExam?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employee_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">Examenes Medicos</a></li>\n");
      out.write("                <li class=\"active\"><a href=\"#\">Notas Medicas</a></li>                \n");
      out.write("              </ul><!-- .nav nav-tabs -->\n");
      out.write("\n");
      out.write("              <div id=\"myModal\" class=\"modal fade\">\n");
      out.write("                <div class=\"modal-dialog\">\n");
      out.write("                  <div class=\"modal-content\">\n");
      out.write("                    <div class=\"modal-header modal-header-danger\">\n");
      out.write("                      <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">&times;</button>\n");
      out.write("                      <h4 class=\"modal-title\"><i class=\"fa fa-warning\"></i> Atenci&#243;n</h4>                          \n");
      out.write("                    </div><!-- .modal-header -->\n");
      out.write("                    <div class=\"modal-body\">\n");
      out.write("                      <p></p>\n");
      out.write("                    </div><!-- .modal-body -->\n");
      out.write("                  </div><!-- .modal-content -->\n");
      out.write("                </div><!-- .modal-dialog -->\n");
      out.write("              </div><!-- .modal fade -->  \n");
      out.write("\n");
      out.write("              <div class=\"tab-content\">\n");
      out.write("                <div class=\"tab-pane fade in active\" id=\"medicalExam\">\n");
      out.write("                  <div class=\"panel-body\">\n");
      out.write("                    <div class=\"panel panel-default\">\n");
      out.write("                      <div class=\"panel-heading\">\n");
      out.write("                        <h4 class=\"panel-title\">Nota Medica</h4>  \n");
      out.write("                      </div><!-- .panel-heading -->\n");
      out.write("\n");
      out.write("                      ");
      if (_jspx_meth_form_005fform_005f0(_jspx_page_context))
        return;
      out.write("<!-- #newForm -->                        \n");
      out.write("                    </div><!-- .panel panel-default -->\n");
      out.write("                  </div><!-- .panel-body -->\n");
      out.write("                </div><!-- .tab-pane fade in active -->\n");
      out.write("              </div><!-- .tab-content -->\n");
      out.write("\n");
      out.write("            </div><!-- .panel-body -->          \n");
      out.write("          </div><!-- .panel-body -->   \n");
      out.write("        </div><!-- . row -->\n");
      out.write("      </div><!-- .container -->  \n");
      out.write("\n");
      out.write("      <script>\n");
      out.write("        var current_date = new Date();\n");
      out.write("        $( \"#datepicker\" ).datepicker({\n");
      out.write("          dateFormat: \"dd-mm-yy\",\n");
      out.write("          buttonImage: \"https://ssl.mackinaw-city.com/newreservations/images/date-picker.png\",\n");
      out.write("          defaultDate: current_date\n");
      out.write("        });                      \n");
      out.write("      </script>      \n");
      out.write("\n");
      out.write("    </body>\n");
      out.write("\n");
      out.write("  </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_form_005fform_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:form
    org.springframework.web.servlet.tags.form.FormTag _jspx_th_form_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005fmethod_005faction.get(org.springframework.web.servlet.tags.form.FormTag.class);
    _jspx_th_form_005fform_005f0.setPageContext(_jspx_page_context);
    _jspx_th_form_005fform_005f0.setParent(null);
    // /WEB-INF/pages/medicalNote.jsp(64,22) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fform_005f0.setAction("/medem/addMedicalNote");
    // /WEB-INF/pages/medicalNote.jsp(64,22) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fform_005f0.setMethod("POST");
    // /WEB-INF/pages/medicalNote.jsp(64,22) name = modelAttribute type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fform_005f0.setModelAttribute("MedicalNote");
    int[] _jspx_push_body_count_form_005fform_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_form_005fform_005f0 = _jspx_th_form_005fform_005f0.doStartTag();
      if (_jspx_eval_form_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\n");
          out.write("                        <div class=\"panel-body\">\n");
          out.write("                        \n");
          out.write("                              <div class=\"panel panel-primary\" id=\"medicalNoteType\">\n");
          out.write("                                <div class=\"panel-heading\">\n");
          out.write("                                  Tipo de Nota\n");
          out.write("                                </div><!-- .panel-heading -->\n");
          out.write("                                <div class=\"panel-body\">\n");
          out.write("                                  <div class=\"row\">\n");
          out.write("                                    <div class=\"col-sm-2\">\n");
          out.write("                                      <label>\n");
          out.write("                                        <input type=\"radio\" name=\"type\" value=\"1\" /> Seguimiento\n");
          out.write("                                      </label>\n");
          out.write("                                    </div><!-- .col-sm-2 -->\n");
          out.write("                                    <div class=\"col-sm-2\">\n");
          out.write("                                      <label>\n");
          out.write("                                        <input type=\"radio\" name=\"type\" value=\"2\" /> Consulta\n");
          out.write("                                      </label>\n");
          out.write("                                    </div><!-- .col-sm-2 -->\n");
          out.write("                                  </div><!-- .row -->\n");
          out.write("                                </div><!-- .panel-body -->\n");
          out.write("                              </div><!-- .panel panel-primay -->                          \n");
          out.write("                          \n");
          out.write("\n");
          out.write("                              <div class=\"panel panel-primary\" id=\"personalNonPatologicals\">\n");
          out.write("                                <div class=\"panel-heading\">\n");
          out.write("                                  Signos vitales\n");
          out.write("                                </div><!-- .panel-heading -->                        \n");
          out.write("                                <div class=\"panel-body\">\n");
          out.write("                                  <div class=\"col-sm-6\">\n");
          out.write("                                    <div class=\"panel panel-default\">\n");
          out.write("                                      <div class=\"panel-body\">\n");
          out.write("                                        <div class=\"row\">\n");
          out.write("                                          <div class=\"form-group\">\n");
          out.write("                                            <label for=\"heartRate\" class=\"col-sm-6\">Frecuencia cardiaca:</label>\n");
          out.write("                                            <div class=\"col-sm-6\">\n");
          out.write("                                              <input type=\"text\" class=\"form-control required\" id=\"heartRate\" name=\"heartRate\" data-name=\"frecuencia cardiaca\" placeholder=\"Latidos por minuto\"/>\n");
          out.write("                                            </div><!-- .col-sm-4 -->                       \n");
          out.write("                                          </div><!-- .form-group -->\n");
          out.write("                                        </div><!-- .row -->  \n");
          out.write("                                        <div class=\"form_divider\"></div>    \n");
          out.write("                                        <div class=\"row\">\n");
          out.write("                                          <div class=\"form-group\">\n");
          out.write("                                            <label for=\"bloodPressure\" class=\"col-sm-6\">Tensi&#243;n arterial:</label>\n");
          out.write("                                            <div class=\"col-sm-6\">\n");
          out.write("                                              <input type=\"text\" class=\"form-control required\" id=\"bloodPressure\" name=\"bloodPressure\" data-name=\"presion arterial\" placeholder=\"mm/Hg\"/>\n");
          out.write("                                            </div><!-- .col-sm-4 -->                      \n");
          out.write("                                          </div><!-- .form-group -->\n");
          out.write("                                        </div><!-- .row -->  \n");
          out.write("                                        <div class=\"form_divider\"></div>\n");
          out.write("                                        <div class=\"row\">\n");
          out.write("                                          <div class=\"form-group\">\n");
          out.write("                                            <label for=\"respiratoryRate\" class=\"col-sm-6\">Frecuencia respiratoria:</label>\n");
          out.write("                                            <div class=\"col-sm-6\">\n");
          out.write("                                              <input type=\"text\" class=\"form-control required\" id=\"respiratoryRate\" name=\"respiratoryRate\" data-name=\"frecuencia respiratoria\" placeholder=\"Respiraciones por minuto\"/>\n");
          out.write("                                            </div><!-- .col-sm-4 -->                        \n");
          out.write("                                          </div><!-- .form-group -->\n");
          out.write("                                        </div><!-- .row --> \n");
          out.write("                                        <div class=\"form_divider\"></div>\n");
          out.write("                                        <div class=\"row\">\n");
          out.write("                                          <div class=\"form-group\">\n");
          out.write("                                            <label for=\"temperature\" class=\"col-sm-6\">Temperatura:</label>\n");
          out.write("                                            <div class=\"col-sm-6\">\n");
          out.write("                                              <input type=\"text\" class=\"form-control required\" id=\"temperature\" name=\"temperature\" data-name=\"temperatura\" placeholder=\"&#176;C\"/>\n");
          out.write("                                            </div><!-- .col-sm-4 -->                      \n");
          out.write("                                          </div><!-- .form-group -->\n");
          out.write("                                        </div><!-- .row -->\n");
          out.write("                                        <div class=\"form_divider\"></div>\n");
          out.write("                                        <div class=\"row\">\n");
          out.write("                                          <div class=\"form-group\">\n");
          out.write("                                            <label for=\"weight\" class=\"col-sm-6\">Peso:</label>\n");
          out.write("                                            <div class=\"col-sm-6\">\n");
          out.write("                                              <input type=\"text\" class=\"form-control required\" id=\"weight\" name=\"weight\" data-name=\"peso\" placeholder=\"kg\"/>\n");
          out.write("                                            </div><!-- .col-sm-4 -->                      \n");
          out.write("                                          </div><!-- .form-group -->\n");
          out.write("                                        </div><!-- .row -->        \n");
          out.write("                                      </div><!-- .panel-body -->\n");
          out.write("                                    </div>\n");
          out.write("                                  </div><!-- .col-sm-6 -->\n");
          out.write("                                  <div class=\"col-sm-6\">\n");
          out.write("                                    <div class=\"panel panel-default\">\n");
          out.write("                                      <div class=\"panel-body\">\n");
          out.write("                                        <div class=\"row\">\n");
          out.write("                                          <div class=\"form-group\">\n");
          out.write("                                            <label for=\"size\" class=\"col-sm-6\">Talla:</label>\n");
          out.write("                                            <div class=\"col-sm-6\">\n");
          out.write("                                              <input type=\"text\" class=\"form-control required\" id=\"size\" name=\"size\" data-name=\"talla\" placeholder=\"m\"/>\n");
          out.write("                                            </div><!-- .col-sm-4 -->                    \n");
          out.write("                                          </div><!-- .form-group -->\n");
          out.write("                                        </div><!-- .row -->  \n");
          out.write("                                        <div class=\"form_divider\"></div>\n");
          out.write("                                        <div class=\"row\">\n");
          out.write("                                          <div class=\"form-group\">\n");
          out.write("                                            <label for=\"username\" class=\"col-sm-6\">IMC:</label>\n");
          out.write("                                            <div class=\"col-sm-6\">\n");
          out.write("                                              <input type=\"text\" class=\"form-control\" id=\"imc\" name=\"username\" placeholder=\"\" readonly=true />\n");
          out.write("                                            </div><!-- .col-sm-4 -->                       \n");
          out.write("                                          </div><!-- .form-group -->\n");
          out.write("                                        </div><!-- .row --> \n");
          out.write("                                        <div class=\"form_divider\"></div>\n");
          out.write("                                        <div class=\"row\">\n");
          out.write("                                          <div class=\"form-group\">\n");
          out.write("                                            <label for=\"waist\" class=\"col-sm-6\">Circunferencia de la cintura:</label>\n");
          out.write("                                            <div class=\"col-sm-6\">\n");
          out.write("                                              <input type=\"text\" class=\"form-control required\" id=\"waist\" name=\"waist\" data-name=\"circunferencia de cintura\" placeholder=\"cm\" />\n");
          out.write("                                            </div><!-- .col-sm-4 -->                       \n");
          out.write("                                          </div><!-- .form-group -->\n");
          out.write("                                        </div><!-- .row -->\n");
          out.write("                                        <div class=\"form_divider\"></div>\n");
          out.write("                                        <div class=\"row\">\n");
          out.write("                                          <div class=\"form-group\">\n");
          out.write("                                            <label for=\"hips\" class=\"col-sm-6\">Circunferencia de la cadera:</label>\n");
          out.write("                                            <div class=\"col-sm-6\">\n");
          out.write("                                              <input type=\"text\" class=\"form-control required\" id=\"hips\" name=\"hips\" data-name=\"circunferencia de cadera\" placeholder=\"cm\" />\n");
          out.write("                                            </div><!-- .col-sm-4 -->                       \n");
          out.write("                                          </div><!-- .form-group -->\n");
          out.write("                                        </div><!-- .row -->        \n");
          out.write("                                        <div class=\"form_divider\"></div>\n");
          out.write("                                        <div class=\"row\">\n");
          out.write("                                          <div class=\"form-group\">\n");
          out.write("                                           <label for=\"weightIndex\" class=\"col-sm-6\">Indice sobrepeso</label>\n");
          out.write("                                           <div class=\"col-sm-6\">\n");
          out.write("                                             <select name=\"weightIndex\" id=\"weightIndex\" class=\"form-control\" readonly=true tabindex=\"17\">\n");
          out.write("                                               <option value=\"\"></option>\n");
          out.write("                                               <option value=\"0\">Sin Sobrepeso</option>\n");
          out.write("                                               <option value=\"1\">Sobrepeso</option>\n");
          out.write("                                               <option value=\"2\">Obesidad 1</option>\n");
          out.write("                                               <option value=\"3\">Obesidad 2</option>\n");
          out.write("                                               <option value=\"4\">Obesidad 3</option>\n");
          out.write("                                              </select><!-- .form-control --> \n");
          out.write("                                            </div><!-- .col-sm-6 -->                    \n");
          out.write("                                          </div><!-- .form-group -->\n");
          out.write("                                        </div><!-- .row -->          \n");
          out.write("                                      </div><!-- .panel-body -->\n");
          out.write("                                    </div>\n");
          out.write("                                  </div><!-- .col-sm-6 -->  \n");
          out.write("                                </div><!-- .panel-body -->\n");
          out.write("                              </div><!-- .panel panel-primary -->\n");
          out.write("\n");
          out.write("                              <div class=\"panel panel-primary\">\n");
          out.write("                                <div class=\"panel-heading\">\n");
          out.write("                                  Hallazgos exploraci&#243;n fisica\n");
          out.write("                                </div><!-- .panel-heading -->                        \n");
          out.write("                                <div class=\"panel-body\">\n");
          out.write("                                  <label for=\"findings\">Descripci&#243;n</label>\n");
          out.write("                                  <textarea class=\"form-control\" rows=\"5\" id=\"findings\" name=\"findings\"></textarea>\n");
          out.write("                                </div><!-- .panel-body -->\n");
          out.write("                              </div><!-- .panel panel-primary -->\n");
          out.write("\n");
          out.write("                              <div class=\"panel panel-primary\" id=\"examDiagnosis\">\n");
          out.write("                                <div class=\"panel-heading\">\n");
          out.write("                                  Diagn&#243;sticos\n");
          out.write("                                </div><!-- .panel-heading -->                        \n");
          out.write("                                <div class=\"panel-body\">\n");
          out.write("                                  <div class=\"row\">\n");
          out.write("                                    <div class=\"col-sm-2\">\n");
          out.write("                                      <label>\n");
          out.write("                                        <input type=\"checkbox\" name=\"diagnosis\" value=\"1\" /> Sano\n");
          out.write("                                      </label>\n");
          out.write("                                    </div><!-- .col-sm-2 -->\n");
          out.write("                                    <div class=\"col-sm-2\">\n");
          out.write("                                      <label>\n");
          out.write("                                        <input type=\"checkbox\" name=\"diagnosis\" value=\"2\" /> Diabetes\n");
          out.write("                                      </label>\n");
          out.write("                                    </div><!-- .col-sm-2 -->\n");
          out.write("                                    <div class=\"col-sm-2\">\n");
          out.write("                                      <label>\n");
          out.write("                                        <input type=\"checkbox\" name=\"diagnosis\" value=\"3\" /> Hipertensi&#243;n\n");
          out.write("                                      </label>\n");
          out.write("                                    </div><!-- .col-sm-2 -->\n");
          out.write("                                    <div class=\"col-sm-2\">\n");
          out.write("                                      <label>\n");
          out.write("                                        <input type=\"checkbox\" name=\"diagnosis\" value=\"4\" /> Dislipidemia\n");
          out.write("                                      </label>\n");
          out.write("                                    </div><!-- .col-sm-2 -->\n");
          out.write("                                    <div class=\"col-sm-2\">\n");
          out.write("                                      <label>\n");
          out.write("                                        <input type=\"checkbox\" name=\"diagnosis\" value=\"5\" /> Otros\n");
          out.write("                                      </label>\n");
          out.write("                                    </div><!-- .col-sm-2 -->                                                     \n");
          out.write("                                  </div><!-- .row -->\n");
          out.write("                                  <div class=\"row\">\n");
          out.write("                                    <div class=\"col-sm-12\">\n");
          out.write("                                      <label for=\"username\">Descripci&#243;n</label>\n");
          out.write("                                      <textarea class=\"form-control\" rows=\"5\" id=\"comment\"></textarea>\n");
          out.write("                                    </div>\n");
          out.write("                                  </div><!-- .row -->\n");
          out.write("                                </div><!-- .panel-body -->\n");
          out.write("                              </div><!-- .panel panel-primary -->\n");
          out.write("\n");
          out.write("                              <div class=\"panel panel-primary\">\n");
          out.write("                                <div class=\"panel-heading\">\n");
          out.write("                                  An&#225;lisis\n");
          out.write("                                </div><!-- .panel-heading -->                        \n");
          out.write("                                <div class=\"panel-body\">\n");
          out.write("                                  <label for=\"analisis\">Descripci&#243;n</label>\n");
          out.write("                                  <textarea class=\"form-control required\" rows=\"5\" id=\"analisis\" name=\"analisis\" data-name=\"analisis\"></textarea>\n");
          out.write("                                </div><!-- .panel-body -->                        \n");
          out.write("                              </div><!-- .panel panel-primary -->\n");
          out.write("\n");
          out.write("                              <div class=\"panel panel-primary\">\n");
          out.write("                                <div class=\"panel-heading\">\n");
          out.write("                                  Tratamiento\n");
          out.write("                                </div><!-- .panel-heading -->                        \n");
          out.write("                                <div class=\"panel-body\">\n");
          out.write("                                  <label for=\"treatment\">Descripci&#243;n</label>\n");
          out.write("                                  <textarea class=\"form-control required\" rows=\"5\" id=\"treatment\" name=\"treatment\" data-name=\"tratamiento\"></textarea>\n");
          out.write("                                </div><!-- .panel-body -->                        \n");
          out.write("                              </div><!-- .panel panel-primary --> \n");
          out.write("                                                 \n");
          out.write("                              <input type=\"hidden\" name=\"employee_id\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employee_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" />\n");
          out.write("                              <button type=\"submit\" class=\"btn btn-block btn-primary\">Generar Nota Medica</button>                         \n");
          out.write("\n");
          out.write("                            ");
          int evalDoAfterBody = _jspx_th_form_005fform_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_form_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005fform_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005fform_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005fform_005f0.doFinally();
      _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005fmethod_005faction.reuse(_jspx_th_form_005fform_005f0);
    }
    return false;
  }
}
