/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2015-05-08 17:28:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class reportCharts_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE>\n");
      out.write("\t<html>\n");
      out.write("\t\t<head>\n");
      out.write("\t\t\t<meta charset=\"utf=8\">\n");
      out.write("      \t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("      \t\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js\"></script>\n");
      out.write("      \t\t<script src=\"bootstrap/bootstrap-3.3.2-dist/js/bootstrap.min.js\"></script>\n");
      out.write("      \t\t<script src=\"js/morris.js-0.5.1/raphael-min.js\"></script>\n");
      out.write("      \t\t<script src=\"js/morris.js-0.5.1/morris.min.js\"></script>\n");
      out.write("      \t\t<link href=\"bootstrap/bootstrap-3.3.2-dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("      \t\t<link rel=\"stylesheet\" href=\"http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css\">\n");
      out.write("\t\t\t<link href=\"css/general_layout_override.css\" rel=\"stylesheet\">\n");
      out.write("\t\t\t<link rel=\"stylesheet\" href=\"js/morris.js-0.5.1/morris.css\">\n");
      out.write("\t\t\t<script src=\"js/main_functions.js\"></script>\n");
      out.write("      \t\t<title>MEDEM :: Reporte</title>\n");
      out.write("\t\t</head>\n");
      out.write("\t\t\n");
      out.write("\t\t<body id=\"reportCharts\">\n");
      out.write("\t\t\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "layouts/navigation_layout.jsp", out, false);
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t  <div class=\"col-md-12\">\n");
      out.write("\t\t\t    <div class=\"row\">\n");
      out.write("\t\t\t      <div class=\"panel panel-default\">\n");
      out.write("\t\t\t        <div class=\"panel-heading\">\n");
      out.write("\t\t\t          <h3 class=\"panel-title\">Reportes <b>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.username }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</b></h3>\n");
      out.write("\t\t\t        </div>\n");
      out.write("\t\t\t        <div class=\"panel-body\">\n");
      out.write("\t\t\t\t\t  <div id=\"myfirstchart\" style=\"height: 250px;\"></div><!-- #myfirstchart--> \t\t          \n");
      out.write("\t\t\t        </div><!-- .panel-body -->\n");
      out.write("\t\t\t      </div><!-- .panel panel-default -->\n");
      out.write("\t\t\t    </div><!--  .row -->\n");
      out.write("\t\t\t  </div><!-- .col-md-12 -->\n");
      out.write("\t\t\t</div>\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "layouts/footer_layout.jsp", out, false);
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("            <div id=\"myModal\" class=\"modal fade\">\n");
      out.write("              <div class=\"modal-dialog\">\n");
      out.write("                <div class=\"modal-content\">\n");
      out.write("                  <div class=\"modal-header modal-header-danger\">\n");
      out.write("                    <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">&times;</button>\n");
      out.write("                    <h4 class=\"modal-title\"><i class=\"fa fa-warning\"></i> Cargando</h4>                          \n");
      out.write("                  </div><!-- .modal-header -->\n");
      out.write("                  <div class=\"modal-body\">\n");
      out.write("                    <p></p>\n");
      out.write("                  </div><!-- .modal-body -->\n");
      out.write("                </div><!-- .modal-content -->\n");
      out.write("              </div><!-- .modal-dialog -->\n");
      out.write("            </div><!-- .modal fade\" -->\n");
      out.write("\t\t\n");
      out.write("\t\t</body>\n");
      out.write("\n");
      out.write("\t\t<script>\n");
      out.write("          generateLineGraph = function(){\n");
      out.write("            Morris.Donut({\n");
      out.write("              element: \"myfirstchart\",\n");
      out.write("              data:[\n");
      out.write("                { label: 'Diabetes', value: 20 },\n");
      out.write("                { label: 'Hipertension', value: 10 },\n");
      out.write("                { label: 'Dislipidemia', value: 5 },\n");
      out.write("                { label: 'Sanos', value: 5 },\n");
      out.write("                { label: 'Otras', value: 50 }\n");
      out.write("              ],\n");
      out.write("              colors:[\n");
      out.write("                \"#43AEA8\",\n");
      out.write("                \"#60B1CC\",\n");
      out.write("                \"#DF6A78\",\n");
      out.write("                \"#DF6A78\",\n");
      out.write("                \"#F4AD49\"\n");
      out.write("              ],\n");
      out.write("              labelColor: '#000',\n");
      out.write("              resize: true\n");
      out.write("            });\n");
      out.write("          }\n");
      out.write("        \n");
      out.write("          generateLineGraph();\n");
      out.write("      </script>\n");
      out.write("\t</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
