/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2015-05-25 18:20:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class showCompany_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE>\n");
      out.write("    <head>\n");
      out.write("      <meta charset=\"utf=8\">\n");
      out.write("      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("      <link rel=\"stylesheet\" href=\"http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css\">\n");
      out.write("      <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js\"></script>\n");
      out.write("      <link href=\"/medem/bootstrap/bootstrap-3.3.2-dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("      <link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css\">\n");
      out.write("      <link href=\"/medem/css/custom.css\" rel=\"stylesheet\">\n");
      out.write("      <link href=\"/medem/css/general_layout_override.css\" rel=\"stylesheet\">\n");
      out.write("      <script src=\"/medem/bootstrap/bootstrap-3.3.2-dist/js/bootstrap.min.js\"></script>\n");
      out.write("      <script src=\"http://code.jquery.com/ui/1.11.4/jquery-ui.js\"></script>\n");
      out.write("\t  <script type='text/javascript' src=\"http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.js\"></script>\n");
      out.write("\t  <script type='text/javascript' src=\"http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/additional-methods.js\"></script>\n");
      out.write("      <script src=\"/medem/js/main_functions.js\"></script>\n");
      out.write("      <title>MEDEM :: Empresa :: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</title>\n");
      out.write("    </head>\n");
      out.write("\n");
      out.write("    <body id=\"companyShow\">\n");
      out.write(" \n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "layouts/navigation_layout.jsp", out, false);
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "layouts/modal_delete_layout.jsp", out, false);
      out.write("\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t  <div class=\"col-md-12\">\n");
      out.write("\t\t\t    <div class=\"row\">\n");
      out.write("\t\t\t      <div class=\"panel panel-default form\">\n");
      out.write("\t\t\t        <div class=\"panel-body\">\n");
      out.write("\t\t\t          <div class=\"col-md-3\">\n");
      out.write("\t\t\t            <div class=\"profile-sidebar\">\n");
      out.write("\t\t\t\t\t\t  <div class=\"profile-usertitle\">\n");
      out.write("\t\t\t\t\t\t    <div class=\"profile-usertitle-name\">\n");
      out.write("\t\t\t\t\t\t      <h1><span class=\"glyphicon glyphicon-certificate\"></span></h1>\n");
      out.write("\t\t\t\t\t\t\t  ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(" \n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<hr class=\"divider\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"profile-creation\">\n");
      out.write("\t\t\t\t\t\t\t  <p><small class=\"text-muted text-left\"><i class=\"glyphicon glyphicon-time\"></i> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.createdAt }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</small></p>\n");
      out.write("\t\t\t\t\t\t\t  <p><small class=\"text-info text-left\"><i class=\"glyphicon glyphicon-user\"></i> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.main_doctor }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</small></p>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<hr class=\"divider\">\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t<div class=\"profile-userbuttons\">\n");
      out.write("\t\t\t\t\t\t\t  <a href=\"/medem/editCompany/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" class=\"btn btn-warning btn-sm\"><span class=\"glyphicon glyphicon-edit\"></span> Editar</a>\n");
      out.write("\t\t\t\t\t\t\t  <a href=\"#\" data-href=\"/medem/deleteCompany/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" class=\"btn btn-danger btn-sm\" data-toggle=\"modal\" data-target=\"#confirm-delete\"><span class=\"glyphicon glyphicon-remove-circle\"></span> Eliminar</a>\n");
      out.write("\t\t\t\t\t\t\t</div><!--. profile-userbuttons -->\n");
      out.write("\t\t\t\t\t\t  </div><!-- .profile-usertitle -->\t              \t      \t\t\t            \t\n");
      out.write("\t\t\t            </div><!-- .profile-sidebar -->\n");
      out.write("\t\t\t          </div><!-- .col-md-3 -->\n");
      out.write("\t\t\t          <div class=\"col-md-9\">\n");
      out.write("\t\t\t            <div class=\"row\">\n");
      out.write("\t\t\t              <div class=\"form-group\" id=\"businessName\">\n");
      out.write("                            <label>Razón social</label>\n");
      out.write("                            <input name=\"businessName\" type=\"text\" class=\"form-control\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.bussinesName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" readonly/>\n");
      out.write("                          </div><!-- .form-group -->\n");
      out.write("                          <hr class=\"divider\">\n");
      out.write("\t\t\t              <div class=\"form-group\" id=\"employeeRegistration\">\n");
      out.write("                            <label>Registro laboral</label>\n");
      out.write("                            <input name=\"employeeRegistration\" type=\"text\" class=\"form-control\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.employeeRegistration}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" readonly/>\n");
      out.write("                          </div><!-- .form-group -->\n");
      out.write("                          <hr class=\"divider\"> \n");
      out.write("\t\t\t              <div class=\"form-group\" id=\"activity\">\n");
      out.write("                            <label>Actividad/Giro</label>\n");
      out.write("                            <input name=\"activity\" type=\"text\" class=\"form-control\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.activity.activity}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" readonly/>\n");
      out.write("                          </div><!-- .form-group -->\n");
      out.write("                          <hr class=\"divider\"> \n");
      out.write("\t\t\t              <div class=\"form-group\" id=\"activity\">\n");
      out.write("                            <label>Creado por</label>\n");
      out.write("                            <input name=\"userName\" type=\"text\" class=\"form-control\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.createdBy}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" readonly/>\n");
      out.write("                          </div><!-- .form-group -->                          \n");
      out.write("                          <hr class=\"divider\">\n");
      out.write("                          <a href=\"/medem/areas/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" class=\"btn btn-primary\"><span class=\"glyphicon glyphicon-flag\"></span> Ver áreas de la empresa</a>                                                                       \n");
      out.write("\t\t\t            </div><!-- .row -->\n");
      out.write("\t\t\t          </div><!-- .col-md-9 -->\n");
      out.write("\t\t\t        </div><!-- .panel-body -->\n");
      out.write("\t\t\t      </div><!-- .panel panel-default form -->\n");
      out.write("\t\t\t    </div><!-- .row -->\t\n");
      out.write("\t\t\t  </div><!-- .col-md-12 -->\n");
      out.write("\t\t\t</div><!-- .container -->     \n");
      out.write("\t\t\t\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "layouts/footer_layout.jsp", out, false);
      out.write(" \n");
      out.write("    </body>\n");
      out.write("    \n");
      out.write("    <script>\n");
      out.write("      $(\"#confirm-delete\").on(\"show.bs.modal\", function(e) {\n");
      out.write("        $(this).find(\".btn-ok\").attr(\"href\", $(e.relatedTarget).data(\"href\"));\n");
      out.write("      });\n");
      out.write("    </script>\n");
      out.write("\n");
      out.write("  </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
